# Spring Boot Config
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# AWS S3 Settings (Passed dynamically in EKS)
aws.region=${AWS_REGION:us-east-1}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:first-american-vault-bucket}

# AWS RDS Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# Application Name used across Datadog/Grafana
spring.application.name=firstamerican-backend

# OpenTelemetry OTLP Exporter Configuration
management.otlp.tracing.endpoint=http://otel-collector:4318/v1/traces
management.tracing.sampling.probability=1.0

# Include trace_id and span_id in Spring Boot Logs automatically
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]